package com.example.main_page.ui.enum_class

enum class PlatformsEnum(val platform: String) {
    PC("PC"),
    IOS("iOS"),
    ANDROID("Android"),
    MAC_OS("macOS"),
    LINUX("Linux"),
    GAMECUBE("GameCube"),
    CLASSIC_MACINTOSH("Classic Macintosh"),
    APPLE_II("Apple II"),
    COMMODORE_AMIGA("Commodore / Amiga"),
    GENESIS("Genesis"),
    DREAMCAST("Dreamcast"),
    _3DO("3DO"),
    JAGUAR("Jaguar"),
    GAME_GEAR("Game Gear"),
    NEO_GEO("Neo Geo"),
    SEGA_SATURN("SEGA Saturn"),
    SEGA_CD("SEGA CD"),
    SEGA_32X("SEGA 32X"),
    SEGA_MASTER_SYSTEM("SEGA Master System"),
    ATARI_7800("Atari 7800"),
    ATARI_5200("Atari 5200"),
    ATARI_2600("Atari 2600"),
    ATARI_8BIT("Atari 8-bit"),
    ATARI_ST("Atari ST"),
    ATARI_LYNX("Atari Lynx"),
    ATARI_XEGS("Atari XEGS"),
    ATARI_FLASHBACK("Atari Flashback"),
    GAME_BOY_ADVANCE("Game Boy Advance"),
    GAME_BOY_COLOR("Game Boy Color"),
    GAME_BOY("Game Boy"),
    WII_U("Wii U"),
    WII("Wii"),
    XBOX_ONE("Xbox One"),
    XBOX("Xbox"),
    XBOX360("Xbox 360"),
    XBOX_SERIES("Xbox Series S/X"),
    PS5("PlayStation 5"),
    PS4("PlayStation 4"),
    PS3("PlayStation 3"),
    PS2("PlayStation 2"),
    PS("PlayStation"),
    PS_VITA("PS Vita"),
    PSP("PSP"),
    NINTENDO_SWITCH("Nintendo Switch"),
    NINTENDO_3DS("Nintendo 3DS"),
    NINTENDO_DS("Nintendo DS"),
    NINTENDO_DSI("Nintendo DSi"),
    NINTENDO_64("Nintendo 64"),
    SNES("SNES"),
    NES("NES")
}